import { ClickMode, HoverMode, MoveDirection, OutMode } from "tsparticles-engine";

export const splitUserFromEmail = (email:string) => {
  const emailUser = email.split('@')[0];
  return emailUser.charAt(0).toUpperCase() + emailUser.slice(1)
}

export const FLAGS = [
    "United Arab Emirates",
    "Andorra",
    "Afghanistan",
    "Antigua And Barbuda",
    "Antigua And Barbuda",
    "Anguilla",
    "Albania",
    "Armenia",
    "Angola",
    "Antarctica",
    "Argentina",
    "American Samoa",
    "Austria",
    "Australia",
    "Aruba",
    "åland Islands",
    "Azerbaijan",
    "Bosnia And Herzegovina",
    "Barbados",
    "Bangladesh",
    "Belgium",
    "Burkina Faso",
    "Bulgaria",
    "Bahrain",
    "Burundi",
    "Benin",
    "Saint Barthélemy",
    "Bermuda",
    "Brunei Darussalam",
    "Bolivia",
    "Bonaire",
    "Brazil",
    "The Bahamas",
    "Bhutan",
    "Bouvet Island",
    "Botswana",
    "Belarus",
    "Belize",
    "The Cocos Islands",
    "Democratic Republic Of Congo",
    "The Central African Republic",
    "Congo",
    "Switzerland",
    "Côte D'ivoire",
    "The Cook Islands",
    "Chile",
    "Cameroon",
    "China",
    "Colombia",
    "Costa Rica",
    "Cuba",
    "Cabo Verde",
    "Curaçao",
    "Christmas Island",
    "Cyprus",
    "Czechia",
    "Germany",
    "Djibouti",
    "Denmark",
    "Dominica",
    "Dominican Republic",
    "Algeria",
    "Ecuador",
    "Estonia",
    "Egypt",
    "Western Sahara",
    "Eritrea",
    "Spain",
    "Ethiopia",
    "European Union",
    "Finland",
    "Fiji",
    "The Falkland Islands",
    "The Federated States Of Micronesia",
    "The Faroe Islands",
    "France",
    "Gabon",
    "England",
    "Northern Ireland",
    "Scotland",
    "Wales",
    "The United Kingdom Of Great Britain And Northern Ireland",
    "Grenada",
    "Georgia",
    "French Guiana",
    "Guernsey",
    "Ghana",
    "Gibraltar",
    "Greenland",
    "Gambia",
    "Guinea",
    "Guadeloupe",
    "Equatorial Guinea",
    "Greece",
    "South Georgia And The South Sandwich Islands",
    "Guatemala",
    "Guam",
    "Guinea-bissau",
    "Guyana",
    "Hong Kong",
    "Heard Island And Mcdonald Islands",
    "Honduras",
    "Croatia",
    "Haiti",
    "Hungary",
    "Indonesia",
    "Ireland",
    "Israel",
    "Isle Of Man",
    "India",
    "The British Indian Ocean Territory",
    "Iraq",
    "Iran",
    "Iceland",
    "Italy",
    "Jersey",
    "Jamaica",
    "Jordan",
    "Japan",
    "Kenya",
    "Kyrgyzstan",
    "Cambodia",
    "Kiribati",
    "The Comoros",
    "Saint Kitts And Nevis",
    "The Democratic People's Republic Of Korea",
    "The Republic Of Korea",
    "Kuwait",
    "The Cayman Islands",
    "Kazakhstan",
    "The Lao People's Democratic Republic",
    "Lebanon",
    "Saint Lucia",
    "Liechtenstein",
    "Sri Lanka",
    "Liberia",
    "Lesotho",
    "Lithuania",
    "Luxembourg",
    "Latvia",
    "Libya",
    "Morocco",
    "Monaco",
    "The Republic Of Moldova",
    "Montenegro",
    "Saint Martin",
    "Madagascar",
    "The Marshall Islands",
    "Republic Of North Macedonia",
    "Mali",
    "Myanmar",
    "Mongolia",
    "Macao",
    "The Northern Mariana Islands",
    "Martinique",
    "Mauritania",
    "Montserrat",
    "Malta",
    "Mauritius",
    "Maldives",
    "Malawi",
    "Mexico",
    "Malaysia",
    "Mozambique",
    "Namibia",
    "New Caledonia",
    "Niger",
    "Norfolk Island",
    "Nigeria",
    "Nicaragua",
    "Netherlands",
    "Norway",
    "Nepal",
    "Nauru",
    "Niue",
    "New Zealand",
    "Oman",
    "Panama",
    "Peru",
    "French Polynesia",
    "Papua New Guinea",
    "Philippines",
    "Pakistan",
    "Poland",
    "Saint Pierre And Miquelon",
    "Pitcairn",
    "Puerto Rico",
    "Palestine",
    "Portugal",
    "Palau",
    "Paraguay",
    "Qatar",
    "Réunion",
    "Romania",
    "Serbia",
    "Russian Federation",
    "Rwanda",
    "Saudi Arabia",
    "Solomon Islands",
    "Seychelles",
    "Sudan",
    "Sweden",
    "Singapore",
    "Saint Helena",
    "Slovenia",
    "Svalbard And Jan Mayen",
    "Slovakia",
    "Sierra Leone",
    "San Marino",
    "Senegal",
    "Somalia",
    "Suriname",
    "South Sudan",
    "Sao Tome And Principe",
    "El Salvador",
    "Sint Maarten",
    "Syrian Arab Republic",
    "Eswatini",
    "The Turks And Caicos Islands",
    "Chad",
    "The French Southern Territories",
    "Togo",
    "Thailand",
    "Tajikistan",
    "Tokelau",
    "Timor-leste",
    "Turkmenistan",
    "Tunisia",
    "Tonga",
    "Turkey",
    "Trinidad And Tobago",
    "Tuvalu",
    "Taiwan",
    "United Republic Of Tanzania",
    "Ukraine",
    "Uganda",
    "The United States Minor Outlying Islands",
    "The United States Of America",
    "Uruguay",
    "Uzbekistan",
    "The Holy See",
    "Saint Vincent And The Grenadines",
    "Venezuela",
    "British Virgin Islands",
    "Us Virgin Islands",
    "Viet Nam",
    "Vanuatu",
    "Wallis And Futuna",
    "Samoa",
    "Kosovo",
    "Yemen",
    "Mayotte",
    "South Africa",
    "Zambia",
    "Zimbabwe"
]

export const particlesConfig = {
    background: {
      color: {
        value: "#000"
      }
    },
    fpsLimit: 120,
    interactivity: {
      events: {
        onClick: {
          enable: true,
          mode: ClickMode.push
        },
        onHover: {
          enable: true,
          mode: HoverMode.repulse
        },
        resize: true
      },
      modes: {
        push: {
          quantity: 4
        },
        repulse: {
          distance: 100,
          duration: 0.4
        }
      }
    },
    particles: {
      color: {
        value: "#ffffff"
      },
      links: {
        color: "#ffffff",
        distance: 150,
        enable: true,
        opacity: 0.5,
        width: 1
      },
      collisions: {
        enable: true
      },
      move: {
        direction: MoveDirection.none,
        enable: true,
        outModes: {
          default: OutMode.bounce
        },
        random: false,
        speed: 1,
        straight: false
      },
      number: {
        density: {
          enable: true,
          area: 800
        },
        value: 180
      },
      opacity: {
        value: 0.5
      },
      shape: {
        type: "circle"
      },
      size: {
        value: {min: 1, max: 5 },
      }
    },
    detectRetina: true
  };